<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <BaseOutputPath>../build/$(MSBuildProjectName)/bin/</BaseOutputPath>
    <BaseIntermediateOutputPath>../build/$(MSBuildProjectName)/obj/</BaseIntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MissionPlanner">
      <HintPath>C:\Program Files (x86)\Mission Planner\MissionPlanner.exe</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="MissionPlanner.Interfaces">
      <HintPath>C:\Program Files (x86)\Mission Planner\Interfaces.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

</Project>
